"""Matchup Predictor V2.1 — Python port of frontend/src/lib/matchupPredictor.ts.

3-Stage Decision Tree:
  Stage 1: 3-way Softmax → P(BB), P(K), P(BIP)
  Stage 2: Base-rate logistic → P(Hit|BIP), P(Out|BIP)
  Stage 3: Base-rate logistic → P(XBH|Hit), P(1B|Hit) → 2B/3B/HR split
"""

import math

# Auto-generated by scripts/compute_matchup_constants.py (2025 season)
MLB_ELO_DISTRIBUTION: dict[str, dict[str, float]] = {
    "BATTER_CONTACT":          {"mean": 1504.5, "std": 33.9},
    "BATTER_POWER":            {"mean": 1468.6, "std": 61.6},
    "BATTER_DISCIPLINE":       {"mean": 1700.3, "std": 139.0},
    "PITCHER_STUFF":           {"mean": 1587.3, "std": 56.6},
    "PITCHER_BIP_SUPPRESSION": {"mean": 1513.3, "std": 18.2},
    "PITCHER_COMMAND":         {"mean": 1681.1, "std": 126.5},
    "PITCHER_CLUTCH":          {"mean": 1500.0, "std": 61.7},
}

MLB_LEAGUE_AVERAGES: dict[str, float] = {
    "bb_rate": 0.0949,
    "k_rate": 0.2218,
    "bip_rate": 0.6834,
    "hit_rate_on_bip": 0.3206,
    "xbh_rate_on_hit": 0.3493,
    "2b_ratio": 0.5522,
    "3b_ratio": 0.0448,
    "hr_ratio": 0.403,
}

ZSCORE_DIVISOR: dict[str, float] = {
    "stage1_bb": 3.5,
    "stage1_k": 3.5,
    "stage2": 5.0,
    "stage3": 5.0,
}

WOBA_WEIGHTS: dict[str, float] = {
    "BB": 0.69,
    "K": 0.0,
    "OUT": 0.0,
    "1B": 0.88,
    "2B": 1.24,
    "3B": 1.56,
    "HR": 2.00,
}


def elo_to_zscore(elo: float, talent_type: str) -> float:
    """Convert ELO to z-score using dimension-specific distribution."""
    dist = MLB_ELO_DISTRIBUTION.get(talent_type)
    if not dist or dist["std"] == 0:
        return 0.0
    return (elo - dist["mean"]) / dist["std"]


def zscore_to_probability(z_diff: float, divisor: float, base_rate: float) -> float:
    """Base-rate logistic: shift logit of base_rate by z_diff/divisor."""
    base_logit = math.log(base_rate / (1.0 - base_rate))
    logit = base_logit + z_diff / divisor
    return 1.0 / (1.0 + math.exp(-logit))


def stage1_softmax(z_disc_cmd: float, z_stuff_contact: float) -> dict[str, float]:
    """Stage 1: 3-way Softmax (BB / K / BIP)."""
    la = MLB_LEAGUE_AVERAGES
    bip_rate = la["bip_rate"]

    base_logit_bb = math.log(la["bb_rate"] / bip_rate)
    base_logit_k = math.log(la["k_rate"] / bip_rate)

    logit_bb = base_logit_bb + z_disc_cmd / ZSCORE_DIVISOR["stage1_bb"]
    logit_k = base_logit_k + z_stuff_contact / ZSCORE_DIVISOR["stage1_k"]

    exp_bb = math.exp(logit_bb)
    exp_k = math.exp(logit_k)
    z = exp_bb + exp_k + 1.0

    return {"pBB": exp_bb / z, "pK": exp_k / z, "pBIP": 1.0 / z}


def predict_plate_appearance(
    batter: dict[str, float],
    pitcher: dict[str, float],
) -> dict:
    """Predict single plate appearance outcome probabilities.

    Args:
        batter: dict with keys contact, power, discipline (ELO values)
        pitcher: dict with keys stuff, bip_suppression, command (ELO values)

    Returns:
        dict with probabilities, expected_woba, z_diffs, stages
    """
    # Z-score conversion
    z_contact = elo_to_zscore(batter["contact"], "BATTER_CONTACT")
    z_power = elo_to_zscore(batter["power"], "BATTER_POWER")
    z_discipline = elo_to_zscore(batter["discipline"], "BATTER_DISCIPLINE")

    z_stuff = elo_to_zscore(pitcher["stuff"], "PITCHER_STUFF")
    z_bip_supp = elo_to_zscore(pitcher["bip_suppression"], "PITCHER_BIP_SUPPRESSION")
    z_command = elo_to_zscore(pitcher["command"], "PITCHER_COMMAND")

    # Z-score diffs
    z_disc_cmd = z_discipline - z_command
    z_stuff_contact = z_stuff - z_contact
    z_contact_bip = z_contact - z_bip_supp

    # Stage 1: Softmax 3-way
    s1 = stage1_softmax(z_disc_cmd, z_stuff_contact)

    # Stage 2: Hit vs Out given BIP
    p_hit_given_bip = zscore_to_probability(
        z_contact_bip, ZSCORE_DIVISOR["stage2"], MLB_LEAGUE_AVERAGES["hit_rate_on_bip"]
    )
    p_hit = s1["pBIP"] * p_hit_given_bip
    p_out = s1["pBIP"] * (1 - p_hit_given_bip)

    # Stage 3: XBH vs Single — pitcher stuff suppresses extra-base hits
    z_stuff_power = z_stuff - z_power
    p_xbh_given_hit = zscore_to_probability(
        -z_stuff_power, ZSCORE_DIVISOR["stage3"], MLB_LEAGUE_AVERAGES["xbh_rate_on_hit"]
    )
    p_1b = p_hit * (1 - p_xbh_given_hit)
    p_xbh = p_hit * p_xbh_given_hit
    p_2b = p_xbh * MLB_LEAGUE_AVERAGES["2b_ratio"]
    p_3b = p_xbh * MLB_LEAGUE_AVERAGES["3b_ratio"]
    p_hr = p_xbh * MLB_LEAGUE_AVERAGES["hr_ratio"]

    probabilities = {
        "BB": s1["pBB"],
        "K": s1["pK"],
        "OUT": p_out,
        "1B": p_1b,
        "2B": p_2b,
        "3B": p_3b,
        "HR": p_hr,
    }

    expected_woba = sum(
        prob * WOBA_WEIGHTS.get(key, 0.0)
        for key, prob in probabilities.items()
    )

    return {
        "probabilities": probabilities,
        "expected_woba": expected_woba,
        "z_diffs": {
            "z_disc_cmd": z_disc_cmd,
            "z_stuff_contact": z_stuff_contact,
            "z_contact_bip": z_contact_bip,
            "z_stuff_power": z_stuff_power,
        },
        "stages": {
            "stage1": s1,
            "stage2": {"p_hit_given_bip": p_hit_given_bip, "p_out_given_bip": 1 - p_hit_given_bip},
            "stage3": {"p_xbh_given_hit": p_xbh_given_hit, "p_1b_given_hit": 1 - p_xbh_given_hit},
        },
    }


# Pre-computed league average wOBA
def _compute_league_avg_woba() -> float:
    la = MLB_LEAGUE_AVERAGES
    hit_rate = la["bip_rate"] * la["hit_rate_on_bip"]
    p_1b = hit_rate * (1 - la["xbh_rate_on_hit"])
    p_xbh = hit_rate * la["xbh_rate_on_hit"]
    return (
        la["bb_rate"] * 0.69
        + p_1b * 0.88
        + p_xbh * la["2b_ratio"] * 1.24
        + p_xbh * la["3b_ratio"] * 1.56
        + p_xbh * la["hr_ratio"] * 2.00
    )


LEAGUE_AVG_WOBA: float = _compute_league_avg_woba()
