"""Matchup Predictor V2.2 — 3-Stage Decision Tree with HBP and dynamic XBH split.

Stages:
  Stage 1: 3-way Softmax → P(BB), P(K), P(BIP); then BB splits into BB + HBP (LR-3)
  Stage 2: Base-rate logistic → P(Hit|BIP), P(Out|BIP)
  Stage 3: Base-rate logistic → P(XBH|Hit), P(1B|Hit) → dynamic 2B/3B/HR split (LR-2)

Key improvements over V2.1:
  ME-2: Batter clutch ELO blends high-leverage PA outcomes
  ME-3: Home-field logit shift to Stage 2 hit probability
  LR-1: ZSCORE_DIVISOR loaded from multi_elo_config.yaml (calibrate via notebooks/)
  LR-2: 2B/3B/HR ratios driven by batter power/speed and pitcher stuff ELO
  LR-3: HBP split from BB post-Stage-1, modulated by pitcher command
"""

import math

from src.fantasy._config import get_config

# ---------------------------------------------------------------------------
# Load calibration config (LR-1: divisors + LR-2: XBH scales)
# ---------------------------------------------------------------------------
_PRED_CFG = get_config()["prediction_engine"]

# LR-1: divisors from config — calibrate with notebooks/calibrate_divisors.ipynb
ZSCORE_DIVISOR: dict[str, float] = _PRED_CFG.get("zscore_divisors", {
    "stage1_bb": 3.5, "stage1_k": 3.5, "stage2": 5.0, "stage3": 5.0, "stage1_hbp": 7.0,
})

# LR-2: XBH split scales from config
_XBH = _PRED_CFG.get("xbh_split_scales", {})
POWER_HR_SCALE: float = _XBH.get("power_hr_scale", 0.05)
STUFF_HR_SCALE: float = _XBH.get("stuff_hr_scale", 0.03)
SPEED_3B_SCALE: float = _XBH.get("speed_3b_scale", 0.008)

# ---------------------------------------------------------------------------
# ELO distributions (auto-generated by scripts/compute_matchup_constants.py)
# ---------------------------------------------------------------------------
MLB_ELO_DISTRIBUTION: dict[str, dict[str, float]] = {
    "BATTER_CONTACT":          {"mean": 1504.5, "std": 33.9},
    "BATTER_POWER":            {"mean": 1468.6, "std": 61.6},
    "BATTER_DISCIPLINE":       {"mean": 1700.3, "std": 139.0},
    "BATTER_SPEED":            {"mean": 1500.0, "std": 50.0},   # LR-2: for 3B ratio
    "PITCHER_STUFF":           {"mean": 1587.3, "std": 56.6},
    "PITCHER_BIP_SUPPRESSION": {"mean": 1513.3, "std": 18.2},
    "PITCHER_COMMAND":         {"mean": 1681.1, "std": 126.5},
    "PITCHER_CLUTCH":          {"mean": 1500.0, "std": 61.7},
}

MLB_LEAGUE_AVERAGES: dict[str, float] = {
    "bb_rate": 0.0949,
    "k_rate": 0.2218,
    "bip_rate": 0.6834,
    "hit_rate_on_bip": 0.3206,
    "xbh_rate_on_hit": 0.3493,
    "2b_ratio": 0.5522,
    "3b_ratio": 0.0448,
    "hr_ratio": 0.403,
}

# ME-2: batter clutch ELO high-leverage blending
CLUTCH_BATTER_MEAN = 1500.0
CLUTCH_BATTER_STD = 57.3   # expected_divisor/2 from batter clutch dimension
HIGH_LEV_FRACTION = 0.20   # ~20% of MLB PAs have LI > 1.5
CLUTCH_PA_SCALE = 0.08     # z-score multiplier for high-leverage prob scaling

# ME-3: home advantage logit shift to Stage 2 hit probability
HOME_LOGIT_SHIFT = 0.010

# LR-3: HBP split parameters
# At league average, ~1.1% of PAs are HBP ≈ 11.6% of the BB bucket (0.011 / 0.0949)
HBP_BASE_FRACTION: float = 0.011 / MLB_LEAGUE_AVERAGES["bb_rate"]
HBP_COMMAND_SCALE: float = 0.015  # higher pitcher command z → lower HBP fraction

WOBA_WEIGHTS: dict[str, float] = {
    "BB": 0.69,
    "HBP": 0.69,   # LR-3: same fangraphs weight as BB
    "K": 0.0,
    "OUT": 0.0,
    "1B": 0.88,
    "2B": 1.24,
    "3B": 1.56,
    "HR": 2.00,
}


def elo_to_zscore(elo: float, talent_type: str) -> float:
    """Convert ELO to z-score using dimension-specific distribution."""
    dist = MLB_ELO_DISTRIBUTION.get(talent_type)
    if not dist or dist["std"] == 0:
        return 0.0
    return (elo - dist["mean"]) / dist["std"]


def zscore_to_probability(z_diff: float, divisor: float, base_rate: float) -> float:
    """Base-rate logistic: shift logit of base_rate by z_diff/divisor."""
    base_logit = math.log(base_rate / (1.0 - base_rate))
    logit = base_logit + z_diff / divisor
    return 1.0 / (1.0 + math.exp(-logit))


def stage1_softmax(z_disc_cmd: float, z_stuff_contact: float) -> dict[str, float]:
    """Stage 1: 3-way Softmax (BB / K / BIP).

    BB here represents the combined 'free base' bucket (true BB + HBP).
    HBP is split out post-Stage-1 in predict_plate_appearance (LR-3).
    """
    la = MLB_LEAGUE_AVERAGES
    bip_rate = la["bip_rate"]

    base_logit_bb = math.log(la["bb_rate"] / bip_rate)
    base_logit_k = math.log(la["k_rate"] / bip_rate)

    logit_bb = base_logit_bb + z_disc_cmd / ZSCORE_DIVISOR["stage1_bb"]
    logit_k = base_logit_k + z_stuff_contact / ZSCORE_DIVISOR["stage1_k"]

    exp_bb = math.exp(logit_bb)
    exp_k = math.exp(logit_k)
    z = exp_bb + exp_k + 1.0

    return {"pBB": exp_bb / z, "pK": exp_k / z, "pBIP": 1.0 / z}


def predict_plate_appearance(
    batter: dict[str, float],
    pitcher: dict[str, float],
    clutch_elo: float = 1500.0,
    is_home: bool = False,
    speed_elo: float = 1500.0,
) -> dict:
    """Predict single plate appearance outcome probabilities.

    Args:
        batter: dict with keys contact, power, discipline (ELO values)
        pitcher: dict with keys stuff, bip_suppression, command (ELO values)
        clutch_elo: batter's clutch ELO — blends high-leverage PA outcomes (ME-2)
        is_home: apply home-field logit boost to hit probability (ME-3)
        speed_elo: batter's speed ELO — drives 3B ratio in XBH split (LR-2)

    Returns:
        dict with probabilities, expected_woba, z_diffs, stages
    """
    # Z-score conversion
    z_contact = elo_to_zscore(batter["contact"], "BATTER_CONTACT")
    z_power = elo_to_zscore(batter["power"], "BATTER_POWER")
    z_discipline = elo_to_zscore(batter["discipline"], "BATTER_DISCIPLINE")
    z_speed = elo_to_zscore(speed_elo, "BATTER_SPEED")  # LR-2

    z_stuff = elo_to_zscore(pitcher["stuff"], "PITCHER_STUFF")
    z_bip_supp = elo_to_zscore(pitcher["bip_suppression"], "PITCHER_BIP_SUPPRESSION")
    z_command = elo_to_zscore(pitcher["command"], "PITCHER_COMMAND")

    # Z-score diffs
    z_disc_cmd = z_discipline - z_command
    z_stuff_contact = z_stuff - z_contact
    z_contact_bip = z_contact - z_bip_supp

    # Stage 1: Softmax 3-way (BB bucket includes HBP at this point)
    s1 = stage1_softmax(z_disc_cmd, z_stuff_contact)

    # LR-3: split BB bucket into pure BB + HBP
    # Higher pitcher command → fewer HBP (better control)
    hbp_fraction = max(0.0, min(0.30, HBP_BASE_FRACTION - z_command * HBP_COMMAND_SCALE))
    p_hbp = s1["pBB"] * hbp_fraction
    p_bb = s1["pBB"] * (1.0 - hbp_fraction)

    # Stage 2: Hit vs Out given BIP
    p_hit_given_bip = zscore_to_probability(
        z_contact_bip, ZSCORE_DIVISOR["stage2"], MLB_LEAGUE_AVERAGES["hit_rate_on_bip"]
    )

    # ME-3: home advantage — logit shift to Stage 2 hit probability
    if is_home:
        logit_hit = math.log(p_hit_given_bip / (1.0 - p_hit_given_bip)) + HOME_LOGIT_SHIFT
        p_hit_given_bip = 1.0 / (1.0 + math.exp(-logit_hit))

    p_hit = s1["pBIP"] * p_hit_given_bip
    p_out = s1["pBIP"] * (1 - p_hit_given_bip)

    # Stage 3: XBH vs Single — pitcher stuff suppresses extra-base hits
    z_stuff_power = z_stuff - z_power
    p_xbh_given_hit = zscore_to_probability(
        -z_stuff_power, ZSCORE_DIVISOR["stage3"], MLB_LEAGUE_AVERAGES["xbh_rate_on_hit"]
    )
    p_1b = p_hit * (1 - p_xbh_given_hit)
    p_xbh = p_hit * p_xbh_given_hit

    # LR-2: dynamic 2B/3B/HR ratios — power drives HR, speed drives 3B, stuff suppresses HR
    hr_raw = max(0.0, MLB_LEAGUE_AVERAGES["hr_ratio"] + z_power * POWER_HR_SCALE - z_stuff * STUFF_HR_SCALE)
    r3b_raw = max(0.0, MLB_LEAGUE_AVERAGES["3b_ratio"] + z_speed * SPEED_3B_SCALE)
    r2b_raw = max(0.0, MLB_LEAGUE_AVERAGES["2b_ratio"])  # 2B stays at league avg as residual
    total_ratio = hr_raw + r3b_raw + r2b_raw
    if total_ratio > 0:
        hr_ratio = hr_raw / total_ratio
        r3b_ratio = r3b_raw / total_ratio
        r2b_ratio = r2b_raw / total_ratio
    else:
        hr_ratio = MLB_LEAGUE_AVERAGES["hr_ratio"]
        r3b_ratio = MLB_LEAGUE_AVERAGES["3b_ratio"]
        r2b_ratio = MLB_LEAGUE_AVERAGES["2b_ratio"]

    p_2b = p_xbh * r2b_ratio
    p_3b = p_xbh * r3b_ratio
    p_hr = p_xbh * hr_ratio

    probabilities = {
        "BB": p_bb,
        "HBP": p_hbp,   # LR-3
        "K": s1["pK"],
        "OUT": p_out,
        "1B": p_1b,
        "2B": p_2b,
        "3B": p_3b,
        "HR": p_hr,
    }

    # ME-2: clutch ELO high-leverage blending
    # ~20% of PAs are high-leverage (LI > 1.5); scale non-K outcomes by clutch z-score
    z_clutch = (clutch_elo - CLUTCH_BATTER_MEAN) / CLUTCH_BATTER_STD if CLUTCH_BATTER_STD > 0 else 0.0
    clutch_mult = 1.0 + z_clutch * CLUTCH_PA_SCALE
    high_lev_probs = {k: (v * clutch_mult if k != "K" else v) for k, v in probabilities.items()}
    probabilities = {
        k: (1.0 - HIGH_LEV_FRACTION) * probabilities[k] + HIGH_LEV_FRACTION * high_lev_probs[k]
        for k in probabilities
    }
    # Renormalize: clutch blend is a multiplicative re-weighting; normalization completes it
    _total_p = sum(probabilities.values())
    probabilities = {k: v / _total_p for k, v in probabilities.items()}

    expected_woba = sum(
        prob * WOBA_WEIGHTS.get(key, 0.0)
        for key, prob in probabilities.items()
    )

    return {
        "probabilities": probabilities,
        "expected_woba": expected_woba,
        "z_diffs": {
            "z_disc_cmd": z_disc_cmd,
            "z_stuff_contact": z_stuff_contact,
            "z_contact_bip": z_contact_bip,
            "z_stuff_power": z_stuff_power,
        },
        "stages": {
            "stage1": s1,
            "stage2": {"p_hit_given_bip": p_hit_given_bip, "p_out_given_bip": 1 - p_hit_given_bip},
            "stage3": {
                "p_xbh_given_hit": p_xbh_given_hit,
                "p_1b_given_hit": 1 - p_xbh_given_hit,
                "hr_ratio": hr_ratio, "3b_ratio": r3b_ratio, "2b_ratio": r2b_ratio,
            },
        },
    }


# Pre-computed league average wOBA (BB and HBP share weight 0.69, so split doesn't change value)
def _compute_league_avg_woba() -> float:
    la = MLB_LEAGUE_AVERAGES
    hit_rate = la["bip_rate"] * la["hit_rate_on_bip"]
    p_1b = hit_rate * (1 - la["xbh_rate_on_hit"])
    p_xbh = hit_rate * la["xbh_rate_on_hit"]
    return (
        la["bb_rate"] * WOBA_WEIGHTS["BB"]   # covers BB + HBP bucket (same weight)
        + p_1b * WOBA_WEIGHTS["1B"]
        + p_xbh * la["2b_ratio"] * WOBA_WEIGHTS["2B"]
        + p_xbh * la["3b_ratio"] * WOBA_WEIGHTS["3B"]
        + p_xbh * la["hr_ratio"] * WOBA_WEIGHTS["HR"]
    )


LEAGUE_AVG_WOBA: float = _compute_league_avg_woba()
